printout_general_path_greedy:
	g++ -O2 --std=c++17 printout_general_path_greedy_test.cc ../models/geo_math.cc ../models/convex_points.cc ../models/spanner_graph.cc ../models/point2d.cc ../algorithms/general_path_greedy.cc ../algorithms/floyd_warshall.cc -o printout_general_path_greedy_test

mc_grid:
	g++ -O2 --std=c++17 monte_carlo_grid.cc ../models/geo_math.cc ../models/convex_points.cc ../models/spanner_graph.cc ../models/point2d.cc ../algorithms/general_path_greedy.cc ../algorithms/floyd_warshall.cc -o monte_carlo_grid

nonplane_grid:
	g++ -O2 --std=c++17 random_grid_nonplane.cc ../models/geo_math.cc ../models/convex_points.cc ../models/spanner_graph.cc ../models/point2d.cc ../algorithms/general_path_greedy.cc ../algorithms/floyd_warshall.cc -o random_grid_nonplane

path_greedy_run:
	g++ -O2 --std=c++17 path_greedy_test.cc ../models/geo_math.cc ../models/convex_points.cc ../models/spanner_graph.cc ../models/point2d.cc ../algorithms/path_greedy.cc ../algorithms/floyd_warshall.cc -o path_greedy_test

printout_path_greedy_run:
	g++ -O2 --std=c++17 printout_path_greedy_test.cc ../models/geo_math.cc ../models/convex_points.cc ../models/spanner_graph.cc ../models/point2d.cc ../algorithms/path_greedy.cc ../algorithms/floyd_warshall.cc -o printout_path_greedy_test